services:
  database:
    image: postgres:15.2
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=plata_dev
    ports:
      - 5432:5432
    volumes:
      - platadata:/var/lib/postgresql/data

volumes:
  platadata:
